version: 2

sources:
  - name: airbyte
    database: dev
    schema: public
    tables:
      - name: _airbyte_raw_events

models:
  - name: events
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: date_created
        description: Date created
      - name: group_id
        description: Issue ID
        tests:
          - unique
          - not_null
      - name: culprit
        description: Error message
      - name: report_type
        description: Report type
        tests:
          - accepted_values:
              values: ['background', 'crash']

  - name: issues
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: total_errors
        description: Total errors

