version: 2

sources:
  - name: airbyte
    database: analytics
    schema: hoho
    tables:
      - name: airbyte_events

models:
  - name: extension_events
    columns:
      - name: date_created
        tests:
          - not_null
      - name: id
        tests:
          - not_null
          - unique
      - name: culprit
      - name: group_id
        tests:
          - not_null
          - unique
      - name: project_id
        tests:
          - not_null
      - name: title
      - name: report_type
        tests:
          - accepted_values:
              values: ['background', 'crash']
          - not_null
